### ISSUE TITLE
mpptd кол-во портов

### ISSUE THREAD

**Issue by galiy** [Osolemio/malina#5]
#define DAEMON_NAME "MPPT Reader daemon"
 
#define PORT_MPPT_ALT0 "/dev/ttyUSB0"
#define PORT_MPPT_ALT1 "/dev/ttyUSB1"
#define PORT_MPPT_ALT2 "/dev/ttyUSB2"
#define PORT_MPPT_ALT3 "/dev/ttyUSB3"
#define PORT_MPPT_ALT4 "/dev/ttyUSB4"
#define BAUDRATE B19200
...
int open_port (int dev)
    {
   int fd;
   if (dev == 1)
        fd = open (PORT_MPPT_ALT0, O_RDWR, O_NOCTTY);
    else if (dev == 2)
	fd = open (PORT_MPPT_ALT1, O_RDWR, O_NOCTTY);
    else if (dev == 3)
	fd = open (PORT_MPPT_ALT2, O_RDWR, O_NOCTTY);
    else if (dev == 4)
	fd = open (PORT_MPPT_ALT3, O_RDWR, O_NOCTTY);
    else
	fd = open (PORT_MPPT_ALT4, O_RDWR, O_NOCTTY);
     
     if (fd < 0)
		{
	syslog(LOG_ERR,"Can't open serial port");
		return -1;
		}

          struct termios port_cfg;

          if (tcgetattr (fd, &port_cfg) < 0)
	{
	 syslog(LOG_ERR, "Error getting serial config");
              return -1;
	}

            
            cfmakeraw (&port_cfg); // All other settings must be after this line
              port_cfg.c_cc[VMIN] = 0;
              port_cfg.c_cc[VTIME] = 1;
            
            cfsetospeed (&port_cfg, BAUDRATE);

          cfsetispeed (&port_cfg, BAUDRATE);

          if (tcsetattr (fd, TCSAFLUSH, &port_cfg) < 0)
		{
          
          syslog(LOG_ERR, "Error entering Daemon. Port setattr");
          return -1;
          
          
          }
	
	if (!isatty (fd))   
          {
          syslog(LOG_ERR, "Not a tty port");
           return -1;
	}

	return fd;
    
  
return -1;
}
...
  //-------------------------Looking for MPPT-----------------------------------
            
	for (i=1;i<=5;i++)
	{
	    if (i>5) { syslog(LOG_ERR, "No MPPT found. Exiting"); return -1;}
	    
	    fd_mppt = open_port (i);

            if (fd_mppt < 0)  
	    {
        	syslog(LOG_NOTICE, "Error open ttyUSB%d. Trying another port....",i-1);
		continue;    
	    }
	
	    send_command(to_read,fd_mppt,0,0);
	 
	    if (read_answer(fd_mppt) != 0) 
	    {
		syslog(LOG_ERR, "Error read eeprom cell. Trying another port...");
		close(fd_mppt);
		continue;
		//return -1;
	    }
	    
	    if (Buffer[1]==5) 
	    {
		syslog(LOG_ERR, "MPPT found on ttyUSB%d. Starting....",i-1);
		break;
	    } 
	    else
	    {
		syslog(LOG_ERR, "MPPT not found on ttyUSB%d.",i-1);
		close(fd_mppt);
	    }
	}     

//----------------------- signals handler ------------------------------

**Comment by Osolemio** [comment]
Спасибо большое за то, что вы обращаете внимание на некоторые вещи.
ПО адаптировано к МАПам разных модификаций, перебор портов адаптирован к ПАК Малина, где могут находиться другие tty устройтва. GCC на Raspbian приводит типы так как меня устраивает. 
Перебирать порты от 0 до 9 - неверное решение. Почему не до 99? Особенно это неверно для ПАК "Малина". Если оно вас устраивает - вы его для себя и оставляете.
Чтение eeprom и пр. сделано опять же с давних модификаций МАП, адаптировано к куче ошибок с разными адапторами и устойчиво работает не первый год. Комплекс "Малина" работает без ошибок и перезагрузок у некоторых клиентов уже более года. Задача не сделать быстрее - задача сделать устойчивее. Вы опробовали алгоритм с одним МАП и на одной платформе. 


Практически все, что вы называете "ошибками" существуют только у вас из-за перехода на другую платформу, другого компилятора. Вы исправили для себя - замечательно. У меня не было задачи делать универсальный код для всех платформ с директивами компилятору.
ПО настроено под работу RaspberryPi, под существующую там mysql, под режимы кеширования и работы с флеш. Для вашей платформы многие вещи могут выглядеть иначе.
Сейчас в разработке Малина-2, где вообще нет Mysql. И все, о чем вы пишете, будет реализовано совершенно иначе
Всего доброго
 
P.S. Код открыт, распространяется "как есть", вы вправе вносить любые правки и изменения.
